--Q1
SELECT
    name,
    marks,
    DECODE(
        SIGN(marks - 90),  1, 'A', 0, 'A',
        DECODE(
            SIGN(marks - 80),  1, 'B', 0, 'B',
            DECODE(
                SIGN(marks - 70),  1, 'C', 0, 'C',
                'F'
            )
        )
    ) AS grade
FROM STUDENTS;

--Q2
CREATE TABLE ORDERS (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    status   CHAR(1)
);

INSERT INTO ORDERS (status) VALUES ('P');
INSERT INTO ORDERS (status) VALUES ('S');
INSERT INTO ORDERS (status) VALUES ('D');
INSERT INTO ORDERS (status) VALUES ('P');

COMMIT;


--Q3
SELECT
    order_id,
    status,
    DECODE(
        status,
        'P', 'Pending',
        'S', 'Shipped',
        'D', 'Delivered',
        'Unknown'
    ) AS status_description
FROM ORDERS;
