--Q1
CREATE TABLE EMP_TEST (
    NAME VARCHAR2(100)
);

INSERT INTO EMP_TEST (NAME) VALUES ('   John Doe   ');
INSERT INTO EMP_TEST (NAME) VALUES ('   Alice   ');
INSERT INTO EMP_TEST (NAME) VALUES ('Bob   ');
INSERT INTO EMP_TEST (NAME) VALUES ('   Carol');

--Q2
SELECT TRIM(NAME) AS CLEAN_NAME
FROM EMP_TEST;

--Q3
SELECT LTRIM(NAME) AS NO_LEADING_SPACES
FROM EMP_TEST;

--Q4
SELECT RTRIM(NAME) AS NO_TRAILING_SPACES
FROM EMP_TEST;

--Q5
INSERT INTO EMP_TEST (NAME) VALUES ('***Mike***');
INSERT INTO EMP_TEST (NAME) VALUES ('##Sara##');

-- Remove '*' from both ends
SELECT TRIM('*' FROM NAME) AS TRIM_STAR
FROM EMP_TEST
WHERE NAME LIKE '*%*';

-- Remove '#' from both ends
SELECT TRIM('#' FROM NAME) AS TRIM_HASH
FROM EMP_TEST
WHERE NAME LIKE '#%#';

SELECT
    NAME AS ORIGINAL,
    TRIM(NAME) AS TRIM_ALL,
    LTRIM(NAME) AS LTRIM_ONLY,
    RTRIM(NAME) AS RTRIM_ONLY,
    TRIM('*' FROM NAME) AS TRIM_STAR,
    TRIM('#' FROM NAME) AS TRIM_HASH
FROM EMP_TEST;
